# wallpaper {
  # monitor = HDMI-A-5
  # path = /home/mwks/Pictures/wallpapers/.jpg
  # fit_mode = cover
# }
wallpaper {
  monitor = DP-3
  path = /home/mwks/Pictures/wallpapers/panor_center.jpg
  fit_mode = cover
}
wallpaper {
  monitor = DP-4
  path = /home/mwks/Pictures/wallpapers/panor_left.jpg
  fit_mode = cover
}
